"""
initial

Revision ID: 5dc14b681055
Revises: 
Create Date: 2025-12-23 18:47:33.048023
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5dc14b681055"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("upload_tokens",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("token", sa.String(length=64), nullable=False),
    sa.Column("download_token", sa.String(length=64), nullable=False),
    sa.Column("max_uploads", sa.Integer(), nullable=False),
    sa.Column("max_size_bytes", sa.BigInteger(), nullable=False),
    sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
    sa.Column("uploads_used", sa.Integer(), nullable=False),
    sa.Column("allowed_mime", sa.JSON(), nullable=True),
    sa.Column("disabled", sa.Boolean(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_upload_tokens_download_token"), "upload_tokens", ["download_token"], unique=True)
    op.create_index(op.f("ix_upload_tokens_id"), "upload_tokens", ["id"], unique=False)
    op.create_index(op.f("ix_upload_tokens_token"), "upload_tokens", ["token"], unique=True)
    op.create_table("uploads",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("token_id", sa.Integer(), nullable=False),
    sa.Column("filename", sa.String(length=255), nullable=True),
    sa.Column("ext", sa.String(length=32), nullable=True),
    sa.Column("mimetype", sa.String(length=128), nullable=True),
    sa.Column("size_bytes", sa.BigInteger(), nullable=True),
    sa.Column("meta_data", sa.JSON(), nullable=False),
    sa.Column("storage_path", sa.String(length=1024), nullable=True),
    sa.Column("upload_length", sa.BigInteger(), nullable=True),
    sa.Column("upload_offset", sa.BigInteger(), nullable=False),
    sa.Column("status", sa.String(length=32), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("completed_at", sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(["token_id"], ["upload_tokens.id"] ),
    sa.PrimaryKeyConstraint("id")
    )
    op.create_index(op.f("ix_uploads_id"), "uploads", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_uploads_id"), table_name="uploads")
    op.drop_table("uploads")
    op.drop_index(op.f("ix_upload_tokens_token"), table_name="upload_tokens")
    op.drop_index(op.f("ix_upload_tokens_id"), table_name="upload_tokens")
    op.drop_index(op.f("ix_upload_tokens_download_token"), table_name="upload_tokens")
    op.drop_table("upload_tokens")
    # ### end Alembic commands ###
